name: Default Pull Request Setting

on:
  pull_request:
    branches:
      main

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: gustavofreze/auto-assign@1.0.0
        with:
          allow_self_assign: true
