name: Default Pull Request Setting

on:
  pull_request:
    branches:
      main

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1.3.1
        with:
          assignees: ${{ github.actor }}
