name: Default Pull Request Setting

on:
  pull_request:
    branches:
      main

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: itsOliverBott/assign-pr-author-as-assignee@release
        with:
          token: ${{ github.token }}
